### ISSUE TITLE
Upon Discord Restart, Volume is adjusted to negative values

### ISSUE THREAD

**Issue by OwDoge42** [yofukashino/VolumeManipulator#1]
Hi! I'm having an issue with this plugin - I only use it on one person, as they are a quiet speaker, to adjust their volume to 200-230%. When I restart discord and return to the voice channel with this user I find them at -77% volume every time. 

Is there a way to save the volume configurations of users, or at least go back to the discord default volume of 100%?

**Comment by yofukashino** [comment]
thanks for letting us know, I am on the issue

**Comment by yofukashino** [comment]
> Hi! I'm having an issue with this plugin - I only use it on one person, as they are a quiet speaker, to adjust their volume to 200-230%. When I restart discord and return to the voice channel with this user I find them at -77% volume every time.
> 
> Is there a way to save the volume configurations of users, or at least go back to the discord default volume of 100%?

okay can you try the new version v1.0.4

you will need to manually download and update it as its not on store. 

lemme know if it fixes the issue

**Comment by yofukashino** [comment]
closing this as resolved due to lack of response
